import 'package:application_caisse/constants/form_suggestions.dart';

/// Liste des produits avec leurs prix par defaut
const List<ProductSuggestion> productsData = [
  ProductSuggestion(designation: 'Impression', prix: 200),
  ProductSuggestion(designation: 'Impression couleur', prix: 300),
  ProductSuggestion(designation: 'Impression RV', prix: 300),
  ProductSuggestion(designation: 'Impression couleur RV', prix: 500),
  ProductSuggestion(designation: 'Impression 140g', prix: 2000),
  ProductSuggestion(designation: 'Impression 230g', prix: 2500),
  ProductSuggestion(designation: 'Impression 300g', prix: 3000),
  ProductSuggestion(designation: 'Impression 230g', prix: 1500),
  ProductSuggestion(designation: 'Impression autocollant', prix: 2000),
  ProductSuggestion(designation: 'Impression sur enveloppe', prix: 500),
  ProductSuggestion(designation: 'Impression sur chemise', prix: 600),
  ProductSuggestion(designation: 'Impression sur chemise RV', prix: 1000),
  ProductSuggestion(designation: 'Modification + Impression', prix: 500),
  ProductSuggestion(
      designation: 'Modification + Impression couleur', prix: 1000),
  ProductSuggestion(designation: 'Scan + Impression', prix: 500),
  ProductSuggestion(designation: 'Scan + Modification + Impression', prix: 600),
  ProductSuggestion(designation: 'Photocopie', prix: 200),
  ProductSuggestion(designation: 'Photocopie couleur', prix: 400),
  ProductSuggestion(designation: 'Photocopie RV', prix: 300),
  ProductSuggestion(designation: 'Photocopie couleur RV', prix: 500),
  ProductSuggestion(designation: 'Sary tapaka 4', prix: 1000),
  ProductSuggestion(designation: 'Sary tapaka 6', prix: 1500),
  ProductSuggestion(designation: 'Sary tapaka 8', prix: 1500),
  ProductSuggestion(designation: 'Sary 10x15', prix: 400),
  ProductSuggestion(designation: 'Plastification A5', prix: 1500),
  ProductSuggestion(designation: 'Plastification A4', prix: 2000),
  ProductSuggestion(designation: 'Plastification CIN', prix: 600),
  ProductSuggestion(designation: 'Reliure', prix: 2000),
  ProductSuggestion(designation: 'Rodoide', prix: 600),
  ProductSuggestion(designation: 'Couverture', prix: 500),
  ProductSuggestion(designation: 'Agrafage', prix: 300),
  ProductSuggestion(designation: 'Papier kraft A4', prix: 500),
  ProductSuggestion(designation: 'Pochette', prix: 300),
  ProductSuggestion(designation: 'Chemise', prix: 500),
  ProductSuggestion(designation: 'Transfert de fichiers', prix: 1000),
  ProductSuggestion(designation: 'Gravage', prix: 1000),
  ProductSuggestion(designation: 'Mise en page', prix: 1500),
  ProductSuggestion(designation: 'Conception', prix: 4000),
  ProductSuggestion(designation: 'Saisie couleur', prix: 1500),
  ProductSuggestion(designation: 'Saisie', prix: 1000),
];
